# Generated by Django 5.2.7 on 2025-10-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmonitoring',
            name='growth_stage',
            field=models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('mature', 'Mature'), ('harvest_ready', 'Harvest Ready')], max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalCrop',
        ),
    ]
