# Generated by Django 5.2.7 on 2025-10-13 18:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_cropmonitoring_growth_stage_and_more'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarketPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mandi_name', models.CharField(help_text='Market/mandi name', max_length=200)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, help_text='Price per quintal in INR', max_digits=10)),
                ('price_date', models.DateField(help_text='Date of price record')),
                ('change_percentage', models.FloatField(default=0.0, help_text='Percentage change from previous day')),
                ('volume', models.IntegerField(default=0, help_text='Volume traded in quintals')),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current price')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('crop', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crops.crop')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Market Price',
                'verbose_name_plural': 'historical Market Prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandi_name', models.CharField(help_text='Market/mandi name', max_length=200)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, help_text='Price per quintal in INR', max_digits=10)),
                ('price_date', models.DateField(help_text='Date of price record')),
                ('change_percentage', models.FloatField(default=0.0, help_text='Percentage change from previous day')),
                ('volume', models.IntegerField(default=0, help_text='Volume traded in quintals')),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-price_date', '-created_at'],
                'unique_together': {('crop', 'mandi_name', 'price_date')},
            },
        ),
    ]
